# Generated by Django 5.2.3 on 2025-06-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Número de teléfono"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=6, unique=True, verbose_name="Código"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor en USD"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("redeemed", "Canjeado"),
                            ("expired", "Expirado"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de canje"
                    ),
                ),
                (
                    "redeemed_at_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_coupons",
                        to="qr_coupons.branch",
                        verbose_name="Sucursal de canje",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="qr_coupons.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
            },
        ),
    ]
