# Generated by Django 5.2.3 on 2025-06-27 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Identificador único",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Código QR",
                "verbose_name_plural": "Códigos QR",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="qr_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="qr_coupons.qrcode",
                verbose_name="Código QR",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("email", "qr_code")},
        ),
    ]
