# Generated by Django 5.2.3 on 2025-06-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0002_qrcode_customer_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="image_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ruta de la imagen"
            ),
        ),
    ]
