# Generated by Django 5.2.3 on 2025-06-27 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0003_qrcode_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="UUID"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="redeemed_at_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qr_coupons.branch",
                verbose_name="Sucursal de canje",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="qr_code",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="qr_coupons.qrcode",
                verbose_name="Código QR",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
    ]
