# Generated by Django 5.2.3 on 2025-06-28 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0004_add_uuid_to_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
    ]
