# Generated by Django 5.2.3 on 2025-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0005_update_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ] 