# Generated by Django 5.2.3 on 2025-06-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0006_fix_branch_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="coupon_value",
            field=models.CharField(
                default="Valor no definido",
                max_length=100,
                verbose_name="Valor del Cupón",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.CharField(max_length=100, verbose_name="Valor"),
        ),
    ]
