# Generated by Django 5.2.3 on 2025-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qr_coupons", "0007_qrcode_coupon_value_alter_coupon_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("email", "qr_code"), ("phone_number", "qr_code")},
        ),
    ]
