services:
  - type: web
    name: tostoqr
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: "./build.sh"
    startCommand: "gunicorn tosto_qr_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tostoqr-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

databases:
  - name: tostoqr-db
    databaseName: tostoqr
    user: tostoqr 