services:
  - type: web
    name: tostoqr
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tosto_qr_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tostoqr-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@tostocoffee.com"
      - key: PLUNK_API_KEY
        value: "sk_550494c612156211f9dfd5e4e4d4161f37f795ccddc5af19"
      - key: PLUNK_SENDER_EMAIL
        value: "noreply@tostocoffee.com"
      - key: PLUNK_SENDER_NAME
        value: "Tosto Coffee"

databases:
  - name: tostoqr-db
    databaseName: tostoqr
    user: tostoqr 